### PR TITLE
Updates to gulpfile to support new rtl scss setup

### PR DESCRIPTION
**Pull request by DreaminDani**
builds rtl files using direction.scss also cleans up runSequence command so there's less repetition of builds.

Build should work on docker-compose up and can be re-run any time by exec-ing into the container and running `npm run build` from the `openemr` working directory.

See the README.md in the interface directory for more info :)

### CODE REVIEW

**Comment by kaplanlior** [comment]
Hi Daniel ( @d3sandoval ), thanks for the PR. Could you also send it upstream to OpenEMR ?

Also, notice your first commit removes a dependency from package.json, but your second commit adds it again. So either meld them together or fix the second commit.

**Comment by DreaminDani** [comment]
@kaplanlior these changes depend on the code in this branch, so I don't feel comfortable merging it upstream separately from it.

As far as the commits go. My first commit introduces two dependencies but I realized that I only needed one of them, so that's why I made another commit for the package.json.

If possible, it'd be best to squash merge this into this branch (making it a single commit), then the original PR #1900 will have all the code necessary to merge to master.

**Comment by DreaminDani** [comment]
Also feel free to copy/paste the code from this branch into the original sassLangDirection bench, I don't mind being kept off the contribution ;)

**Comment by kaplanlior** [comment]
I wasn't aware of  openemr/openemr#1900 . Thanks for the context.

**Comment by bradymiller** [comment]
hi @kaplanlior and @matrix-amiel  ,
Rec cherry-pick of @d3sandoval 2 commits into your matrix-israel:sassLangDirection branch and then pushing that into your PR at https://github.com/openemr/openemr/pull/1900
(then I can merge them all into the main master branch from there)
-brady

**Pull request merged**
